version: "2"
checks:
    argument-count:
      config:
        threshold: 5
    file-lines:
      config:
        threshold: 500
    method-complexity:
      config:
        threshold: 8
    method-lines:
      config:
        threshold: 50
    return-statements:
        config:
          threshold: 5
    similar-code:
      enabled: false
plugins:
  fixme:
      enabled: true
      config:
        strings:
          - todo
          - hack